sudo: required

dist: xenial

os:
  - linux

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

addons:
  apt:
    packages:
      - xvfb

before_script: # configure a headless display to test plot generation
  - export DISPLAY=:99.0
  - which Xvfb
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  # - ls -l /etc/init.d/
  # - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirements.txt
  - pip install -r requirements_docs.txt
  - pip install pytest-cov
  - pip install codecov
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then
      pip install -r requirements_test.txt
    fi
  - pip install -e .
  - which python
  - python -c "import vtk; print(vtk.VTK_VERSION)"
  - python -c "import imageio; imageio.plugins.ffmpeg.download()"
  - pip list

script:
  # Run the test suite and generate coverage report
  - pytest -v --cov vtki
  # Run all code examples in the docstrings
  - pytest -v --doctest-modules vtki
  - |  # report code coverage
    if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then
      codecov
    fi
  # Now make sure notebooks are running
  # TODO: add below: pytest -v --nbval-lax --current-env --disable-warnings tests/*.ipynb;
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 2.7 ]]; then
      pytest -v --nbval-lax --current-env --disable-warnings notebooks/*.ipynb;
    fi
  # And test the documentation
  - cd ./docs/
  - make doctest
  - make html
  # And then clean up and changes from running examples with fileio
  - cd ..
  - git reset --hard # removes staged and working directory changes

cache:
  directories:
  - "$HOME/.cache/pip"

deploy:
  provider: pypi
  user: akaszynski
  distributions: sdist
  on:
    condition: "$TRAVIS_PYTHON_VERSION == 3.6"
    tags: true
  password: $PYPI_PASSWORD

notifications:
  email: false
