environment:

  matrix:
    # vtk python wheel not available for python2.7
    # - PYTHON: "C:\\Python27-x64\\python"
    #   PYTHON_VERSION: "2.7.13"
    #   PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64\\python"
      PYTHON_VERSION: "3.5.2"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64\\python"
      PYTHON_VERSION: "3.6.0"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64\\python"
      PYTHON_VERSION: "3.7.1"
      PYTHON_ARCH: "64"

  # This is a vtki flag to bypass X11 hooks
  ALLOW_PLOTTING: "True"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # Use ci-helpers
  - "git clone --depth 1 git://github.com/vtkiorg/gl-ci-helpers.git"
  - "powershell gl-ci-helpers/appveyor/install_opengl.ps1"
  # Install requirements
  - "%PYTHON% -m ensurepip"
  - "%PYTHON% -m pip install -r requirements.txt"
  - "%PYTHON% -m pip install pytest"
  - "%PYTHON% -m pip install pytest-cov"
  - "%PYTHON% -m pip install pyqt5==5.11.3"
  - "%PYTHON% -m pip install pytest-qt"
  - "imageio_download_bin ffmpeg"

build_script:
  - "%PYTHON% setup.py sdist"
  - "%PYTHON% setup.py install"

# it's not apparent that the root directory changes
# test_qt_plotting.py fails to collect in windows
test_script:
  - "del /Q tests\\test_qt_plotting.py"
  - "cd tests"
  - "%PYTHON% -m pytest --cov -v"
  - "cd .."
