name: pyvista-env
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - jupyterlab
  - numpy
  - vtk
  - scooby>=0.5.1
  - meshio
  - matplotlib
  - imageio>=2.5.0
  - imageio-ffmpeg
  - colorcet
  - cmocean
  - itkwidgets>=0.25.2
  - tqdm
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - hypothesis>=5.8.0
  - pip
  - trimesh
  - rtree
  - pyembree
  - panel
  - ipygany
  - ipyvtklink
  - trame
  - pythreejs
  - pooch
  - pip:
      - pytest-memprof
