name: pyvista-env
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - jupyterlab
  - numpy
  - vtk==9.3.20230807rc0
  - scooby>=0.5.1
  - meshio
  - matplotlib
  - imageio>=2.5.0
  - imageio-ffmpeg
  - colorcet
  - cmocean
  - tqdm
  - pytest
  - pytest-cov
  - pytest-xdist
  - codecov
  - hypothesis>=5.8.0
  - pip
  - trimesh
  - rtree
  - pyembree
  - pooch
  - trame>=2.5.2
  - trame-vuetify>=2.3.1
  - trame-vtk>=2.5.8
  - pip:
      - pytest-memprof
