accept = [
  200, # Link is OK
  403, # Skip domains known to return 403 Forbidden to bots
  429, # Network error: Too Many Requests
]
cache = true
exclude = [
  'file:///home/*',
  'http://861c873f6352:8888/*',
  'https://github.com/pyvista/pyvista/settings/branches',
  'https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/',
  'https://repology.org',
]
exclude_all_private = true # exclude 'localhost', '127.0.0.1', etc.
exclude_path = ['pyvista/core/utilities/docs.py']
extensions = ['md', 'py', 'rst', 'txt']
fail = false
user_agent = 'curl/7.83.1'
verbose = 'info'
