name: Cache vtk-data Repo

on:
  workflow_call:
    outputs:
      cache-path:
        description: Path to vtk-data cache
        value: ${{ jobs.cache-vtk-data.outputs.cache-path }}
      key:
        description: Cache key used for vtk-data
        value: ${{ jobs.cache-vtk-data.outputs.key }}

jobs:
  cache-vtk-data:
    name: Cache vtk-data Repo
    strategy:
      fail-fast: false
      matrix:
        include:
          # need both self-hosted and GitHub hosted to ensure cache is local to runners
          - runner-labels: "ubuntu-22.04-self-hosted"
          - runner-labels: "ubuntu-22.04"

    runs-on: ${{ matrix.runner-labels }}

    outputs:
      cache-path: ${{ steps.set-path.outputs.cache-path }}
      key: ${{ steps.restore.outputs.cache-primary-key }}

    steps:
      - name: Define cache path
        id: set-path
        run: |
          echo "cache-path=${GITHUB_WORKSPACE}/vtk-data" >> "$GITHUB_OUTPUT"

      - name: Get vtk-data commit
        run: |
          echo VTK_DATA_COMMIT=$(git ls-remote https://github.com/pyvista/vtk-data HEAD | awk '{ print $1}') >> $GITHUB_ENV

      - name: Restore vtk-data cache
        id: restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ steps.set-path.outputs.cache-path }}
          key: vtk-data-${{ env.VTK_DATA_COMMIT }}
          lookup-only: true

      - name: Clone vtk-data if cache miss
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: pyvista/vtk-data
          path: ${{ steps.set-path.outputs.cache-path }}

      - name: Save vtk-data cache
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ steps.set-path.outputs.cache-path }}
          key: vtk-data-${{ env.VTK_DATA_COMMIT }}
          enableCrossOsArchive: true
