name: Cache vtk-data Repo

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Runner to run cache on."
        required: true
        type: string
    outputs:
      key:
        description: Cache key used for vtk-data
        value: ${{ jobs.cache-vtk-data.outputs.key }}

permissions:
  id-token: none
  contents: none

jobs:
  cache-vtk-data:
    name: job # Avoid duplicating name since the calling workflow's job name is also used

    #      fail-fast: false
    #      matrix:
    #        # Workflows that re-use this workflow must specify a matrix of runners to use
    #        # For github-hosted runners:
    #        #   - Only ONE runner needs to be specified, since we use "enableCrossOsArchive: true"
    #        #   - E.g. if runner is "ubuntu-22.04", caching will also work for "windows-latest"
    #        # For self-hosted runners:
    #        #   - ALL runners must be specified
    #        #   - E.g. use runner "macos-15-self-hosted,ubuntu-22.04-self-hosted" to enable caching for both runners

    runs-on: ${{ inputs.runs-on }}

    outputs:
      key: ${{ steps.restore.outputs.cache-primary-key }}

    steps:
      - name: Set cache path dirname
        run: |
          # define a reusable variable for the folder name
          echo "VTK_DATA_DIRNAME=vtk-data" >> "$GITHUB_ENV"

      - name: Get vtk-data commit
        run: echo VTK_DATA_COMMIT=$(git ls-remote https://github.com/pyvista/vtk-data HEAD | awk '{ print $1}') >> $GITHUB_ENV

      - name: Restore vtk-data cache
        id: restore
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.VTK_DATA_DIRNAME }}
          key: vtk-data-${{ env.VTK_DATA_COMMIT }}
          lookup-only: true

      - name: Clone vtk-data if cache miss
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v6
        with:
          persist-credentials: false
          repository: pyvista/vtk-data
          path: ${{ env.VTK_DATA_DIRNAME }}

      - name: Save vtk-data cache
        if: steps.restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ env.VTK_DATA_DIRNAME }}
          key: vtk-data-${{ env.VTK_DATA_COMMIT }}
          enableCrossOsArchive: true
