name: Build and Publish Docker Image
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  packages: write

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-22.04
    # For Pull Requests, only runs from `docker`
    if: github.event_name == 'push' ||
      ( github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      startsWith(github.event.pull_request.head.ref, 'docker')
      )
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Create PyVista package
        run: |
          pip install build
          python -m build --sdist

      - name: Log into the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          registry: ${{ env.REGISTRY }}
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for the Jupyter Docker image
        id: jupyter_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push the Jupyter Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: docker/jupyter.Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.jupyter_meta.outputs.tags }}
          labels: ${{ steps.jupyter_meta.outputs.labels }}

      - name: Extract metadata for the Slim Docker image
        id: slim_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
            suffix=-slim,onlatest=true
      - name: Build and push the Slim Docker image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8
        with:
          context: .
          file: docker/slim.Dockerfile
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: ${{ steps.slim_meta.outputs.tags }}
          labels: ${{ steps.slim_meta.outputs.labels }}
