name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi and welcome! Thanks for posting your first issue in the PyVista project! Someone from @pyvista/developers will chime in before too long. If your question is support related, it may be automatically transfered to https://github.com/pyvista/pyvista-support'
        pr-message: >
          ğŸš€ Thanks for opening your first pull request in PyVista! ğŸš€\
          
          Please make sure you read (skim ğŸ˜‰) our [Contributing Guide](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md) and abide by our [Code of Conduct](https://github.com/pyvista/pyvista/blob/master/CODE_OF_CONDUCT.md).
          
          A few things to keep in mind:

          - Remember to run the tests locally to make debugging issues easier.
          - If you need help writing tests, take a look at the existing ones for inspiration. If you don't know where to start, let `@pyvista/developers` know and we'll walk you through it.
          - All new features should be documented. It helps to write the docstrings for your functions/classes before writing the code. This will help you think about your code design and results in better code.
          - No matter what, we are really grateful that you put in the effort to open this PR! â­
    
